#
# Copyright (C) 2015 DING Changchang <archang@canaan-creative.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Avalon
LUCI_DEPENDS:=

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signaturenclude ../../build/module.mk
